### ISSUE TITLE
Add `postcss-plugin` to keywords

### ISSUE THREAD

**Issue by romainmenke** [RocketCommunicationsInc/postcss-custom-property-token-fallback#1]
https://github.com/RocketCommunicationsInc/postcss-custom-property-token-fallback/blob/2c24e4d802a3816222086a3da26fd89d8f6a6650/package.json#L15

We maintain a generated list of postcss plugins but this package won't be included unless the `postcss-plugin` keyword is added in `package.json` : 

https://csstools.github.io/postcss-plugins-directory/

**Comment by micahjones13** [comment]
Fixed - thank you!
